jobs: 200
keep-going: True
restart-times: 1
rerun-incomplete: True
use-singularity: True
max-jobs-per-second: 100
max-status-checks-per-second: 100
configfiles: ["config/config.yaml", "config/config.data.hg19.yaml", "GMS560_config/config/config_production_pipeline_miarka.yaml"]
drmaa: "-p core -t {resources.time} -n {resources.threads} --mem={resources.mem_mb} --mem-per-cpu={resources.mem_per_cpu} {resources.gres} -J {rule} -A ngi2024001 -e slurm/{rule}_%j.err -o slurm/{rule}_%j.out --nodes=1-1"
drmaa-log-dir: "slurm"
singularity-args: "--cleanenv -B /proj -B $TMPDIR:/tmp --nv"
singularity-prefix: "/proj/ngi2024001/nobackup/bin/wp1_gms560/apptainer_cache/"
wrapper-prefix: "git+file://proj/ngi2024001/nobackup/bin/wp1_gms560/v0.24.0/snakemake-wrappers/"
