PROJECT_DESIGN_DATA: "/proj/ngi2024001/nobackup/bin/wp1_gms560/design_and_ref_files"
PROJECT_PON_DATA: "/proj/ngi2024001/nobackup/bin/wp1_gms560/design_and_ref_files"
PROJECT_REF_DATA: "/proj/ngi2024001/nobackup/bin/wp1_gms560/design_and_ref_files"

hydra_local_path: "/proj/ngi2024001/nobackup/bin/wp1_gms560/hydra-genetics"

resources: "GMS560_config/config/resources_production.yaml"

general_report: "config/reports/general_report.yaml"

subsample: "seqtk"

reference:
  background: "{{PROJECT_PON_DATA}}/GMS560/Background/background_panel_nextseq2000_23_dp500_af015.tsv"
  artifacts: "{{PROJECT_PON_DATA}}/GMS560/Artifact/artifact_panel_nextseq2000_combo_53.tsv"
  design_intervals_gatk_cnv: "{{PROJECT_DESIGN_DATA}}/GMS560/design/gatk.preprocessed.xleap_ns2000_22.interval_list"

cnvkit_batch:
  normal_reference: "{{PROJECT_PON_DATA}}/GMS560/PoN/cnvkit_xleap_ns2000_22.cnn"

cnvkit_batch_hrd:
  normal_reference_hrd: "{{PROJECT_PON_DATA}}/GMS560/PoN/cnvkit_nextseq2000_23_HRD.cnn"
 
gatk_denoise_read_counts:
  normal_reference: "{{PROJECT_PON_DATA}}/GMS560/PoN/gatk_cnv_xleap_ns2000_22.hdf5"
    
jumble_run:
  normal_reference: "{{PROJECT_PON_DATA}}/GMS560/PoN/jumble_xleap_ns2000_22.PoN.RDS"

msisensor_pro:
  PoN: "{{PROJECT_PON_DATA}}/GMS560/PoN/Msisensor_pro_reference_xleap_ns2000_22.list_baseline"

msisensor_pro_filter_sites:
  PoN: "{{PROJECT_PON_DATA}}/GMS560/PoN/Msisensor_pro_reference_xleap_ns2000_22.list_baseline"

purecn:
  extra: "--model betabin --mapping-bias-file {{PROJECT_PON_DATA}}/GMS560/PoN/purecn/mapping_bias_xleap_ns2000_22.rds"
  normaldb: "{{PROJECT_PON_DATA}}/GMS560/PoN/purecn/normalDB_xleap_ns2000_22.rds"
  intervals: "{{PROJECT_PON_DATA}}/GMS560/PoN/purecn/targets_twist-gms-st_hg19_25000_xleap_intervals.txt"

purecn_coverage:
  intervals: "{{PROJECT_PON_DATA}}/GMS560/PoN/purecn/targets_twist-gms-st_hg19_25000_xleap_intervals.txt"

seqtk_subsample:
  nr_reads: 150000000
  nr_reads_rna: 30000000
