jobs: 500
keep-going: True
restart-times: 2
rerun-incomplete: True

configfiles: 
  - "config/config.yaml"
  - "config/config.data.hg19.yaml"
  - "GMS560_config/config/Marvin/config_production_pipeline_marvin.yaml"

software-deployment-method: apptainer
apptainer-args: "-e --cleanenv --containall -B /projects -B /data -B /beegfs-storage -B /scratch -B /beegfs-scratch -B /beegfs-scratch/wp4/Twist_Solid_tmp:/tmp -B $HOME"
apptainer-prefix: "/projects/wp4/nobackup/singularity_cache/"

wrapper-prefix: "git+file://projects/wp1/nobackup/ngs/utveckling/workspace/patsm159/build_for_miarka/migrate-to-snakemake9/build/GMS_Solid/GMS_Solid_migrate-to-snakemake9/snakemake-wrappers/"

executor: drmaa
drmaa-args: "-A wp1 -N 1-1 -t {resources.time} -n {threads} --mem={resources.mem_mb} --mem-per-cpu={resources.mem_per_cpu} --partition=hi -J {rule} -e slurm_out/{rule}_%j.err -o slurm_out/{rule}_%j.out"
drmaa-log-dir: "slurm_out"
default-resources:
  - threads=1
  - time="04:00:00"
  - partition="high"
  - mem_mb=3074
  - mem_per_cpu=3074

